expose_php=Off
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
memory_limit=256M
upload_max_filesize=20M
post_max_size=21M
max_execution_time=60
opcache.enable=1
opcache.validate_timestamps=0
